FROM nvidia/cuda:12.8.1-cudnn-runtime-ubuntu24.04

# Install dependencies
RUN pip install ultralytics

# Installing headless version of OpenCV
RUN pip uninstall opencv-python -y
RUN pip install opencv-python-headless
