FROM ubuntu:24.04
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    python3-venv \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Create virtual environment
RUN python3 -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"
RUN pip install --upgrade pip

# Install dependencies
RUN pip install onnx onnxruntime ultralytics

# Installing headless version of OpenCV
RUN pip uninstall opencv-python -y
RUN pip install opencv-python-headless
